"""added workspace

Revision ID: 2300864b2c12
Revises: 601e77a8ffb5
Create Date: 2025-04-21 16:17:55.721904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2300864b2c12'
down_revision = '601e77a8ffb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_space',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_space', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_space_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_space', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_space_name'))

    op.drop_table('work_space')
    # ### end Alembic commands ###
