"""Add workspace thumbnail

Revision ID: 8abf345ca73f
Revises: 81ab64141383
Create Date: 2025-06-08 10:28:53.728123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8abf345ca73f'
down_revision = '81ab64141383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_space', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_space', schema=None) as batch_op:
        batch_op.drop_column('thumbnail')

    # ### end Alembic commands ###
